name: Docker Workflow

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and Test Image
        uses: docker/build-push-action@v2
        with:
          push: false
          context: .
          file: ./Dockerfile
          target: tests
      - name: Push Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sanokhin/ci-example
          context: .
          file: ./Dockerfile
          target: prod
          build-args: |
            GIT_HASH=${{ github.sha }}
