name: Example Workflow

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Use Example Secret
      env:
        SECRET: ${{ secrets.EXAMPLE_SECRET }}
      run: echo "$SECRET"
    - name: Example of Context Usage
      run: echo "${{ github.event_name }}${{ github.ref != 'refs/heads/master' && '-dev' || '' }}"
