name: Example Workflow

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Use Example Secret
      env:
        SECRET: ${{ secrets.EXAMPLE_SECRET }}
      run: echo "$SECRET"
