name: Experiments

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Example Read File
        uses: actions/github-script@v6
        id: get_version
        with:
          script: |
            const fs = require('fs');
            const version = fs.readFileSync('./version.txt', 'utf8').trim();
            console.log(JSON.stringify(version));
            core.setOutput('version', version);
      - name: Check my token
        run: |
          echo "${{ steps.get_version.outputs.version }}"
      - name: Get current dir
        run: |
          ls -l .
          echo "Current dir: $(pwd)"
          echo "Parent dir contents:"
          ls -l ..
          echo "Grand parent dir:"
          ls -l ../..
